### ISSUE TITLE
What could be cause of this? Error: self signed certificate/ ... 'DEPTH_ZERO_SELF_SIGNED_CERT' 

### ISSUE THREAD

**Issue by jgfet** [dzurikmiroslav/rest-client-generator#5]
For this kind of command:
rest-client-generator --output-file services.ts --platform angular2-ts https://unnamedurl.com:9000/tomcatapp/application.wadl
Getting:
Reading WADL from https://unnamedurl.com:9000/tomcatapp/application.wadl
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }

=

No idea why I got the certificate errors. Maybe something wrong with the Tomcat server configuration.

=
It was likely there would have  been an issue, because I'd not supplied a basic authentication header too.

=

I worked around this by downloading to local machine.. 
1) application.wadl 
2) schema.xml.
3) xsd0.xsd

On my Mac, I had to also go into System Preferences > Security & Privacy to allow VSCode to open application.wadl.
In the grammers node I modified:
`<include href="application.wadl/xsd0.xsd">`
to become:
 `<include href="xsd0.xsd">`

Then I ran it on a local file in folder. 
I was just expecting interfaces. 
Having services generated as well was a very pleasant welcome bonus.
Useful project. Many thanks for your efforts.

**Comment by dzurikmiroslav** [comment]
Disabled strictSSL opts for fetching files. Now supports self signed certificate.
