### ISSUE TITLE
There seems to be incomplete conversion of interfaces..

### ISSUE THREAD

**Issue by jgfet** [dzurikmiroslav/rest-client-generator#6]
<img width="390" alt="screen shot 2017-07-28 at 12 32 49" src="https://user-images.githubusercontent.com/28791001/28715720-35bccab4-7391-11e7-91a3-adaf769a915f.png">
<img width="254" alt="screen shot 2017-07-28 at 12 33 16" src="https://user-images.githubusercontent.com/28791001/28715723-3a6292ce-7391-11e7-96e2-3347971223ee.png">
application.wadl/xsd0.xsd (as well as schema.xml) contains the expected constituents. and the interface generated shows no properties.

Also... This manifests itself in quite a few places... missing property names not copied over from schema.xml
<img width="856" alt="screen shot 2017-07-28 at 12 45 19" src="https://user-images.githubusercontent.com/28791001/28716023-df6d9240-7392-11e7-8d45-e64a4bab8994.png">
<img width="246" alt="screen shot 2017-07-28 at 12 45 57" src="https://user-images.githubusercontent.com/28791001/28716027-e4841006-7392-11e7-8a63-66e4a6b4b1e2.png">
<img width="644" alt="screen shot 2017-07-28 at 12 50 09" src="https://user-images.githubusercontent.com/28791001/28716129-62c6a532-7393-11e7-86f7-e3a700c301a1.png">
<img width="294" alt="screen shot 2017-07-28 at 12 50 20" src="https://user-images.githubusercontent.com/28791001/28716131-657bf322-7393-11e7-92c3-0fc7ae4f306a.png">
I've zipped up the documents I used, so you can test against them as well.
[Archive.zip](https://github.com/dzurikmiroslav/rest-client-generator/files/1183078/Archive.zip)

**Comment by dzurikmiroslav** [comment]
Hello, thank you for reporting it. The problem consist of two parts, i made a issues: #7 #8

**Comment by jgfet** [comment]
Hi Miroslav. Thanks for taking a look at this. Does the fixed code need to somehow get pushed to a npm repository again? Because I tried doing an npm uninstall -g rest-client-generator followed by npm install -g rest-client-generator and the issue still seems manifests itself at the moment when I run the conversion.

**Comment by dzurikmiroslav** [comment]
I closed ticket #7 just now... Now you can reinstall rest-client-generator. Ticket #8 still open.

**Comment by jgfet** [comment]
FYI: V 0.2.1 is an improvement. But there are still issues.
<img width="349" alt="screen shot 2017-08-01 at 12 19 11" src="https://user-images.githubusercontent.com/28791001/28823084-d29cc648-76b3-11e7-8565-9fbd8fdf5c6a.png">
<img width="244" alt="screen shot 2017-08-01 at 12 19 29" src="https://user-images.githubusercontent.com/28791001/28823085-d518ca2a-76b3-11e7-83ee-7a523a738219.png">
<img width="242" alt="screen shot 2017-08-01 at 12 19 40" src="https://user-images.githubusercontent.com/28791001/28823088-d8731220-76b3-11e7-8404-116e7792a267.png">
<img width="235" alt="screen shot 2017-08-01 at 12 19 52" src="https://user-images.githubusercontent.com/28791001/28823090-da73e20c-76b3-11e7-898f-075168da51b8.png">
<img width="251" alt="screen shot 2017-08-01 at 12 20 04" src="https://user-images.githubusercontent.com/28791001/28823091-dbfabd94-76b3-11e7-9cc3-decb16e69177.png">

**Comment by jgfet** [comment]
It's nested complex types that are the last hurdle, when a ref, rather than name attribute exists in the xml <xs:sequence>
