### ISSUE TITLE
CamelCase pattern for endpoints and ignore words

### ISSUE THREAD

**Issue by ghost** [dzurikmiroslav/rest-client-generator#9]
I'm using `rest-client-generator` with my Spring Boot project. I want to generate a Typescript client for my Angular2 application.

The generation works so far but the naming looks rather weird sometimes. `authorization-endpoint` becomes:

```typescript
export class AuthorizationendpointService {
  // ..
}
```
Two things would be nice:

- It would be awesome to have it in CamelCase when words are separated with `-`
- An option which would allow one to exclude certain patterns like `-endpoint` completely

E.g. `user-item-endpoint` should become `UserItemService` in the generated `service.ts`.

**Comment by dzurikmiroslav** [comment]
- Non alphabetically characters in names convert next charcater to upper.
`user-item` become `UserItemEndpointService`
- Added options `--service-exclude <value>` & `--method-exclude <value>`
